version: '3'
networks:
  java-docker-app-network:
    ipam: 
      driver: default
      config:
        - subnet: $ENV_SUBNET
services:
  java:
    image: $ENV_OPENJDK
    container_name: java-docker-app_$MODULE_NAME
    volumes:
      - ./bin/jar:/usr/src/app
    working_dir: /usr/src/app
    command: java -jar $MODULE_NAME-$MODULE_VERSION.jar
    networks: 
      java-docker-app-network:
        ipv4_address: $MODULE_IP
    ports: 
      - $MODULE_PORT:8080
  maven:
    image: $ENV_MAVEN
    container_name: java-docker-app_maven
    working_dir: /usr/src/app
    networks: 
      java-docker-app-network:
    volumes:
      - ./app/resources/maven:/root/.m2
      - ./bin/jar:/usr/src/app/build
      - ./app/modules/$MODULE_NAME:/usr/src/app